version: '3.3'

services:

  apieco-application:
    container_name: apieco-application
    command: npm run start:server:production
    build: .
    ports:
      - "3000:3000"
    env_file:
      - production.env
    environment:
      - NODE_ENV=production



